namespace SBRB.Models
{
    /// <summary>
    /// Class used to compose an Items unique ID within the database
    /// </summary>
    public class CompositeItemId: ModDependant
    {
        // Using a uint value generated by the seeder instead of the items name
        // because a mod may contain an object and a generic item who share a common name, but are different otherwise
        public uint ItemId;
    }

    public class ArmorData
    {
        public ArmorTypes ArmorType;
    }

    public class AugmentData
    {
        public string Type;
        public string Name;
        public string DisplayName;
    }

    public class ConsumableData
    {
        public double? FoodValue;
    }

    public class CurrencyData
    {
        public int CurrencyValue;
        public string CurrencyName;
    }

    public class FlashlightData
    {
        public string LightColor;
        public double? BeamLevel;
        public double? BeamAmbience;
    }

    public class LiquidData
    {
        public string Liquid;
    }

    public class MaterialData
    {
        public uint MaterialId;
    }

    public class ObjectData
    {
        public string Race = "generic";
        public bool? Printable;
        public string[] ColonyTags;
    }

    public class ToolData
    {
        public ToolTypes ToolType;
        public uint? BlockRadius;
        public double? FireTime;
        public double? RangeBonus;
        public double? TileDamage;
    }

}
